### ISSUE TITLE
[ML] 'Machline learning flow with Kubernetes' Research

### ISSUE THREAD

**Issue by becleverksh** [becleverksh/hipparchus#1]

**Comment by shsym** [comment]
Related Apache projects (distributed computing)
- Flink: https://flink.apache.org/flink-architecture.html
- Spark: https://spark.apache.org/docs/latest/index.html
- Spark Stream: https://spark.apache.org/docs/latest/streaming-programming-guide.html
- Storm: http://storm.apache.org/index.html

**Comment by shsym** [comment]
* We can use Kafka (+ZooKeeper) cluster for IoT data stream processing.
* Machine learning part (if needed) can be based on Spark ML Pipelines to distribute its workload.
  (Spark MLlib can be used for ease of developing)

- ZooKeeper: https://zookeeper.apache.org/ 
- Spark MLlib: https://spark.apache.org/mllib/
