### ISSUE TITLE
[Research] Self-reflection & Work history

### ISSUE THREAD

**Issue by becleverksh** [becleverksh/hipparchus#25]
* '나는 누구인가?!', '나는 어떤 개발자 인가?!', '나는 어떠한 인생과 삶을 살 것인가.' 등 다양한 주제에 대한 **자아성찰 시간을 갖습니다.**
* 더불어 '컴퓨터 과학'에 대한 **전반적인, 개론적 지식을 연구합니다.**
* **현재 기준으로 많은 아웃풋과 올바른 방향성에 도달 하였으며, 마무리 연구, 깨우침을 얻고 정리하도록 합니다.**
* 해당 이슈의 중요도와 시간은 수치로 환산할 수 없는, 계산할 수 없는 가치이기에 Estimate를 999로 설정합니다.

후후...

**Comment by becleverksh** [comment]
인생에서 굉장히 다시 돌아오지 않을 값진 시간, 터닝포인트가 되었습니다. 생각보다 긍정적인 아웃풋이 너무 많아, 오히려 이런 시간을 가질 수 있었던 것에 감사함을 느낍니다. 👍 

하지만, 오늘은 행복한 주말이기에, 행복한 꿈도리.. 내일까지 휴업 및 휴식을 취합니다.

본 이슈는 차주 월요일부터 재 진행합니다.

**Comment by becleverksh** [comment]
제 기준으로, 사람의 유전적 요소, 혹은 환경적 배경, 개인적 성향 등 다양한 요소들에 의거하여, 어쩌면 누군가에게는 1) 굉장히 이른 시기에 결론에 도달했을 수 있고, 혹은 2) 결론 도출에 유리하게 사용될 수 있는 유전적 요소를 선천적으로 타고났을 수도 있지만, 즉, 사람마다 시기와 속도는 다르지만, 전적으로 악착같이 노력해도, 나 자신을 제대로 파악하지 못하고 올바르지 못한 방향성을 갖고 살아가고 일을 한다면, 그 노력이 그렇게 큰 의미와 영향력을 가지지 못하는 것 같습니다. 달리 간결하게 표현하면, '제 값을 못한다.', '인풋과 아웃풋이 비례하지 않는다.' 표현하면 될 것 같네요.


꽤 상당히 많은 시간과 노력을 투자하여 고민하였고, 삶과 인생에 대한 총체적인, 다양한 측면들이 잘 정리가 되어 **주도적이고, 긍정적인 결론**에 도달하였습니다. 👍

늦은 감도 없지 않지만, **그래도, 지금이라도 정리할 수 있었던 시간과 기회가 있었음에 감사함과 행복감을 느낍니다.**

타인과 사회의 기준에 자신을 흔들리며, 살 생각은 없으며, 끊임없는 자기 계발을 통해 본인이 원하는 삶, 일, 회사를 선택하여, 주도적인, 후회하지 않는 삶을 살려합니다.

해당 이슈는 종료하며, hipparchus 프로젝트 연구 및 개발을 이어 진행합니다.

**Comment by shsym** [comment]
👍👍👍

**Comment by becleverksh** [comment]
술 한 잔 마셨습니다... 
또 다른 방황을 했습니다... 자아성찰이 잘 안돼도 좋습니다.. 인생이 별로 일 수 있습니다... 밤낮으로 고민했습니다...

뒤늦게, 25살 이래로, 나름 주어진 환경에서 아웃풋을 만들려 꽤 고군분투했던 것 같습니다.. 꽤 시간이 지나간 만큼, 뒤돌아 보는 시간도 많이 필요했던 것 같고, 생각의 깊이도 꽤 깊었던 것 같습니다...

약간 삐딱선을 탔지만,  **becleverksh**만을 기억해주세요.

* p.s.
    * becleverksh가 아니라, **noanswerksh**로 계정명을 바꿀까 고민합니다... 
    * 본 이슈는 프로젝트 종료 시까지 진행하고, 혼자 다짐합니다...

**Comment by becleverksh** [comment]
### [ 190411 ]
#### Resetting dev environment
* sublimerge Pro trial 종료로 인한, 다른 diff (compare) plugin 모색
    - Atom : split-diff, compare-files
    - Sublime text : sublimerge 3
        + Pro는 라이센스가 있는데, 3는 없는 듯하다. 단, 비교 알고리즘, UI 퀄리티는 떨어짐.
    - Jetbrains IDE : 기본 compare 기능
        + 비교 알고리즘이 정말 좋은 듯 함.
        + 단, sublime text나 beyondcompare 처럼 뭔가 가볍게쓰기에는 불편함. 단축키도 없고.
    - 돈있으면 유명한 유료 툴(beyondcompare, etc.)쓰고, 없으면 tool에 맞게 무료 plugin 사용
* zshrc, oh-my-zsh & vim plugins 재설정
    - `macOS 10.14 mojave`에서 homebrew 기반으로 설치한 oh-my-zsh plugin들의 path를 못찾는다는 로그가 발생함.
        + https://github.com/robbyrussell/oh-my-zsh/issues/7688
        + `~/.oh-my-zsh/custom/plugins` 또는 `~/.oh-my-zsh/plugins`에 설치하면 됨.
    - zsh, oh-my-zsh, zshrc, vimrc, zsh-autosuggestions, zsh-syntax-highlighting, erics_vim_syntax_and_color_highlighting 등 컨셉 재검토
* 개인 연구 및 개발 폴더 트리 재정리
    - 전반적인 개발환경 구축하기 위한 부분
        + terminal, ide tools, mac, docker, git, npm
    - 전체 wiki 리스트

<br>

#### Github
* wiki repository `public` -> `private`
* issues 생성
    - #26
    - #27

<br>

#### Research : #27
* SW license 
    - free, open-source, free and open-source 컨셉 정리
    - free & open-source 차이 및 비교

<br>

#### Etc.
* Mojave 10.14.3 -> 10.14.4 upgrade

**Comment by becleverksh** [comment]
### [ 190411 ]
#### Research : #27
* SW license 
    - free, open-source, free and open-source SW 컨셉 정리
    - free / open-source 차이 및 비교
    - 일반적인 free and open-source SW License 검토
        + GPL, LPGL, BSD, Apache, MIT, MPL
            * 이 안에서도, Permissive, Weakly Protective, Strongly Protective License 그룹으로 나뉨.
            * Permissive : Public Domian, MIT, BSD, Apache
            * Weakly Protective : LGPLv2.1, LGPLv2.1+, LGPLv3, LGPLv3+, MPL
            * Strongly Protective : GPLv2, GPLv2+, GPLv3
    - 생각보다, 컨셉, 히스토리가 어려움(깊게 파면 끝도없다는 느낌). 정확히/완벽히는 모르겠으나, 전체적이고, 핵심적이고, 개략적인 그림만 파악하고 끝기로.
        + 만약 해당 라이센스에 포함되는 소프트웨어를 수정 및 재배포하는 경우라면, 이에 대한 상세스펙을 확인해야함. (컨트리뷰터...)
    - 결론
        + **free나 open-source나 소프트웨어의 자유로운 공개, 수정, 배포를 공통적으로 추구. 결론적으로 같은 개념이므로, 대부분 같은 라이센스를 리스트업함(이것이 핵심). 단, 약간의 차이가 있음.**
            * 컨셉 차이
                - free는 사회적 운동 - 사용자를 넘어 인간에게 있어 'free' 윤리적 목표에 충실하여 소프트웨어를 다룬다는 컨셉
                - open-source는 개발 방법론 - 소스 개발의 효율성 증진을 위한 관점에서 바라본다는 컨셉
            * 또한, 오픈소스 라이센스의 경우에는 **'소스는 오픈하지만, 수정 및 재배포가 불가능하거나, 특정 그룹에게만 열려있는 경우'**가 존재함. 이에 따라서 일부적으로는 자유 소프트웨어의 이념을 벗어나는 경우가 있음.
        + **결론적으로, 두 컨셉의 출발점, 정의, 그룹은 서로 각기 다르지만, 추구하는 개념은 같기 때문에, 결국 같은 라이센스들을 포함한다. 단, 일부의 경우에는 서로 겹치지 않는, 예외적인 부분들이 존재한다. 그리고 결국에는 두 개념이 'free and open source software'으로 귀결된다.**
            * 컨셉 출현 순서
                - free -> open-source -> free and open-source
                - free and open-source : free와 open-source 이념을 모두 만족하는 소프트웨어
                - 이에 따라서, 일반적으로 널리 알려진 라이센스(e.g. GPL, LGPL, BSD, Apache, MIT)들 모두 free and open-source software license이다.
        + 이러한 흐름과 개념들이 있지만, 일반적으로는 '오픈 소스'라는 명칭으로 대부분 사용하는 것 같다.

**Comment by becleverksh** [comment]
### [ 190412 ]
#### Research : #27
* Wiki > fundamental, fundamental-software-engineering, common-linux 정리
    - fundamental.md : Web / Back-end Server Developer로써 필요한 기본 역량 자료
    - fundamental-software-engineering.md : SW Devlopment & Engineering 자료
    - common-linux.md : 리눅스 관련 자료
* SW Devlopment & Engineering 정리
    - Software Development
        + Core activities, Paradigms and models, Frameworks and methodologies, Supporting disciplines, Practices, Tools
    - Software Engineering
    - Software Design
        + Design Pattern (GoF)
    - Software Configuration Management
        + Software Versioning (SemVer)
    - Programming Paradigm
        + OOP
* ZenHub 컨셉 정리
    - GitHub에 유용한 Plugin
    - **Chrome extension 기능 기반**  
        + ZenHub board, reports 기능 사용 가능
        + Slack, Gitter 연동 가능
        + Issue에 `Pipelines, Estiate (like Story point), Release, Epics` 등 기능 추가

**Comment by becleverksh** [comment]
### [ 190413 ]
#### Research : #27
* 프로젝트 공유 문서 작성 및 공유 (to @shsym)
    - 일정 개요
    - GitHub 프로토콜
        + ZenHub 사용
            * 적용 전후 비교
            * 특징
            * Estimate 측정
        + Issue 관리
            * 생성
        + Shortcut
    - Software Development
        + Agile
        + SemVer

**Comment by becleverksh** [comment]
Slack-ZenHub 연동 테스트 - Comment

**Comment by becleverksh** [comment]
Slack-GitHub 연동 테스트 - Comment

**Comment by becleverksh** [comment]
코멘트 중요한데...

**Comment by becleverksh** [comment]
다시 테스트

**Comment by becleverksh** [comment]
### [ 190412 ]
#### Research : #27
* Wiki > fundamental, fundamental-software-engineering, common-linux 정리
    - fundamental.md : Web / Back-end Server Developer로써 필요한 기본 역량 자료
    - fundamental-software-engineering.md : SW Devlopment & Engineering 자료
    - common-linux.md : 리눅스 관련 자료
* SW Devlopment & Engineering 정리
    - Software Development
        + Core activities, Paradigms and models, Frameworks and methodologies, Supporting disciplines, Practices, Tools
    - Software Engineering
    - Software Design
        + Design Pattern (GoF)
    - Software Configuration Management
        + Software Versioning (SemVer)
    - Programming Paradigm
        + OOP
* ZenHub 컨셉 정리
    - GitHub에 유용한 Plugin
    - **Chrome extension 기능 기반**  
        + ZenHub board, reports 기능 사용 가능
        + Slack, Gitter 연동 가능
        + Issue에 `Pipelines, Estimate (like Story point), Release, Epics` 등 기능 추가 

<br>


### [ 190413 ]
#### Research : #27
* 프로젝트 공유 문서 작성 및 공유 (to @shsym)
    - 일정 개요
    - GitHub 프로토콜
        + ZenHub 사용
            * 적용 전후 비교
            * 특징
            * Estimate 측정
        + Issue 관리
            * 생성
        + Shortcut
    - Software Development
        + Agile
        + SemVer


<br>

### [ 190413 ]
### 1. 일정 공유
* @shsym, 4/28 ~ 5/5 컨퍼런스 참가

<br>

### 2. 프로젝트 협업 환경 구축
* 사용 툴 정의
    - JamBoard, Skype : 회의 용도
    - OneNote : 정리된, Specific한 스펙들 기술
    - OneDrive : 공식화된 기술 스펙 설명 문서
    - GitHub, ZenHub, Slack : 개발 용도

<br>

### 3. Slack 셋팅
workspace : winet (https://winet-lab.slack.com/)

#### 3.1. OneNote
* Zapier 사용 
    - 참고) Zapier와 비슷한 Microsoft Flow를 이용해서 할 수 있음. 단, Slack사에 정식적으로 리뷰받지 못함. 그래서, 정상 구동이 잘 안됨. 이에 따라서, Zapier 사용
    1. zapier.com 회원가입 
    2. 새로운 Zap 생성: Onenote -> Slack 
    3. 사이트 내 step 따라서 인증 진행 
        + Onenote: New Note in Section 옵션 - 후킹 대상 Onenote section 선택 
        + Slack: Send Channel Message 옵션 - Onenote 정보 중 title과 web-page link 활용 
        + Message format <URL|URL이 적용될 TEXT> 
    4. 생성된 Zap의 이름 설정 및 ON 

<br>

#### 3.2. JamBoard
* Jamboard는 Google drive에 저장되므로 google drive를 적용 
* Channel이나 message에서 google drive 파일을 공유하듯이 공유 가능 - URL 형태로 공유됨

<br>

#### 3.3. GitHub
1. Slack > GitHub App 설치
2. App Setting (ref. [Docs link](#https://github.com/integrations/slack)) 
    - Subscribing repository
        ```
        # Manual
        /github subscribe owner/repo [feature]
        /github unsubscribe owner/repo [feature]

        # e.g.
        /github subscribe becleverksh/hipparchus
        /github unsubscribe becleverksh/hipparchus
        /github subscribe becleverksh/hipparchus comments
        /github subscribe becleverksh/hipparchus reviews comments
        /github unsubscribe owner/respository reviews,comments
        ```

        + Configuration
            * enabled by default
                - issues - Opened or closed issues
                - pulls - New or merged pull requests
                - statuses - Statuses on pull requests
                - commits - New commits on the default branch (usually master)
                - deployments - Updated status on deployments
                - public - A repository switching from private to public
                - releases - Published releases
                - **단, Comment에 대한 Noti는 발생하지 않으며, 이는 disabled 되어 있음.**
            * disabled by default
                - reviews - Pull request reviews
                - comments - New comments on issues and pull requests
                - branches - Created or deleted branches
                - commits:all - All commits pushed to any branch
            * 참고)
                - comment:edit의 경우에는 노티는 안가지만, 슬랙에 내용이 반영됨. 
                - comment:delete는 노티가 안감.

<br>

#### 3.3. ZenHub
1. ZenHub App 설치
2. `ZenHub Dashboard` Setting에서 `Slack & integrations > Connect Slack to ZenHub` 설정

<br>

#### 3.4. OneDrive
* OneDrive App 설치 : 단순히, 파일 공유 링크, '+' 버튼 기능 수행 시 OneDrive 기능 추가됨.
* File Notification
    - 파일 생성 / 수정 시 Notification은 불가능
        + Microsoft Flow를 이용하여 연동하려 했지만, 테스트는 가능하나 실제 파일 수정시 노티가 안옴.
        + Zapier도 불가능

<br>

#### 3.5. GoogleDrive
* OneDrive와 동일

<br>

**Comment by becleverksh** [comment]
Slack log 채널에 남깁니다. 이슈 종료합니다.
